"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@supabase/supabase-js";
import {Check,LockKeyhole,Plus,Save,Trash2} from "lucide-react";
import config from "@/data/supabase-config.json";
import {products as fallback,Product,Variant} from "@/lib/catalog";
type Draft=Product;
export function CatalogAdmin(){
 const [db]=useState(()=>createClient(config.url,config.publishableKey));const [signed,setSigned]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[query,setQuery]=useState(""),[items,setItems]=useState<Product[]>(fallback),[selected,setSelected]=useState("");
 useEffect(()=>{(async()=>{const {data:{user}}=await db.auth.getUser();if(user?.email!=="envases3g@gmail.com"||!user.email_confirmed_at)return;setSigned(true);const {data}=await db.from("products").select("slug,name,data").order("name").limit(1000);if(data?.length)setItems(data.map(x=>x.data as Product));})();},[db]);
 const matches=useMemo(()=>items.filter(p=>`${p.name} ${p.slug} ${p.category}`.toLowerCase().includes(query.toLowerCase())).slice(0,80),[items,query]);const product=items.find(p=>p.slug===selected);const [draft,setDraft]=useState<Draft|null>(null);
 async function login(){setMessage("");const {error}=await db.auth.signInWithOtp({email:"envases3g@gmail.com",options:{emailRedirectTo:window.location.origin+"/administracion/catalogo"}});setMessage(error?"No pudimos enviar el acceso.":"Revisá el correo envases3g@gmail.com y abrí el enlace de acceso.");}
 function choose(p:Product){setSelected(p.slug);setDraft(structuredClone(p));setMessage("");}
 function update(field:keyof Draft,value:string|boolean){setDraft(d=>d?({...d,[field]:value} as Draft):d)}
 function variant(i:number,field:keyof Variant,value:string|boolean){setDraft(d=>{if(!d)return d;const variants=d.variants.map((v,n)=>n===i?({...v,[field]:field==="price"||field==="minQuantity"?Number(value):value} as Variant):v);return {...d,variants,price:variants.length?Math.min(...variants.map(v=>v.price)):null};});}
 async function save(){if(!draft)return;setBusy(true);setMessage("");const {error}=await db.from("products").update({name:draft.name,data:draft}).eq("slug",draft.slug);if(error)setMessage("No se pudo guardar. Verificá que tu cuenta tenga permisos de administrador.");else{setItems(old=>old.map(p=>p.slug===draft.slug?draft:p));setMessage("Cambios guardados y publicados en el catálogo.");}setBusy(false);}
 if(!signed)return <section className="admin-login"><LockKeyhole size={34}/><span className="eyebrow">CATÁLOGO PRIVADO</span><h1>Editar productos</h1><p>Acceso exclusivo para modificar textos, imágenes, precios y accesorios.</p><strong>envases3g@gmail.com</strong><button className="button primary" onClick={login}>Recibir enlace de acceso</button>{message&&<p role="status">{message}</p>}</section>;
 return <section className="catalog-admin"><div className="section-heading"><div><span className="eyebrow">ENVASES 3G · ADMINISTRACIÓN</span><h1>Editar catálogo</h1><p>Los cambios se guardan en Supabase y actualizan la web.</p></div><a className="text-link" href="/administracion/pedidos">Ver pedidos</a></div><div className="catalog-admin-layout"><aside className="admin-product-list"><input aria-label="Buscar producto" placeholder="Buscar producto o slug…" value={query} onChange={e=>setQuery(e.target.value)}/><span>{matches.length} resultados</span>{matches.map(p=><button key={p.slug} className={selected===p.slug?"selected":""} onClick={()=>choose(p)}>{p.name}<small>{p.category}</small></button>)}</aside><div className="admin-editor">{!draft?<div className="empty"><Check size={36}/><h2>Elegí un producto</h2><p>Podés editar toda su información y sus accesorios.</p></div>:<><div className="editor-heading"><div><span className="eyebrow">{draft.category}</span><h2>{draft.name}</h2></div><button className="button primary" onClick={save} disabled={busy}><Save size={18}/>{busy?"Guardando…":"Guardar cambios"}</button></div><div className="editor-fields"><label>Nombre<input value={draft.name} onChange={e=>update("name",e.target.value)}/></label><label>Descripción<textarea value={draft.description} onChange={e=>update("description",e.target.value)}/></label><label>Imagen principal (URL)<input value={draft.image} onChange={e=>update("image",e.target.value)}/></label><label className="check-row"><input type="checkbox" checked={draft.available} onChange={e=>update("available",e.target.checked)}/> Publicado como disponible</label></div><div className="variant-editor"><div className="editor-heading"><div><h3>Variantes y accesorios</h3><p className="fine">Cada fila puede ser una tapa, gatillo, válvula, color o presentación.</p></div><button className="button outline" onClick={()=>setDraft(d=>d?({...d,variants:[...d.variants,{id:"nuevo-"+Date.now(),name:"Nuevo accesorio",price:0,available:true,minQuantity:1}]}) : d)}><Plus size={18}/>Agregar variante</button></div>{draft.variants.map((v,i)=><div className="variant-row" key={v.id}><input aria-label="Nombre de variante" value={v.name} onChange={e=>variant(i,"name",e.target.value)}/><label>Precio<input type="number" min="0" step="0.01" value={v.price} onChange={e=>variant(i,"price",e.target.value)}/></label><label>Mínimo<input type="number" min="1" value={v.minQuantity} onChange={e=>variant(i,"minQuantity",e.target.value)}/></label><label className="check-row"><input type="checkbox" checked={v.available} onChange={e=>variant(i,"available",e.target.checked)}/> Disponible</label><button className="icon-button" aria-label={"Eliminar "+v.name} onClick={()=>setDraft(d=>d?({...d,variants:d.variants.filter((_,n)=>n!==i)}):d)}><Trash2 size={18}/></button></div>)}</div></>}</div></div></section>;
}
