"use client";
import {useCallback,useEffect,useState} from "react";
import {createClient} from "@supabase/supabase-js";
import {LockKeyhole,RefreshCw,LogOut,Package} from "lucide-react";
import config from "@/data/supabase-config.json";
import {currency} from "@/lib/catalog";
import {adminEmails} from "@/lib/supabase";
type Order={id:string;number:number;created_at:string;customer_name:string;phone:string;total:number;status:string;items:{name:string;variant:string;quantity:number;unitPrice:number;subtotal:number}[]};
const statuses:Record<string,string>={nuevo:"Nuevo",en_contacto:"En contacto",confirmado:"Confirmado",completado:"Completado",cancelado:"Cancelado"};
export function OrdersPanel(){
 const [db]=useState(()=>createClient(config.url,config.publishableKey));
 const [signed,setSigned]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[orders,setOrders]=useState<Order[]>([]),[filter,setFilter]=useState(""),[search,setSearch]=useState(""),[email,setEmail]=useState("itsloloyt@gmail.com");
 const refresh=useCallback(async()=>{setLoading(true);const {data:{user}}=await db.auth.getUser();
  if(!user?.email||!adminEmails.includes(user.email)||!user.email_confirmed_at){setSigned(false);setOrders([]);setLoading(false);return;}
  setSigned(true);const {data,error}=await db.from("orders").select("id,number,created_at,customer_name,phone,items,total,status").order("created_at",{ascending:false}).limit(500);
  if(error)setMessage("No pudimos cargar los pedidos. Intentá actualizar.");else{setOrders((data||[]) as Order[]);setMessage("");}setLoading(false);
 },[db]);
 useEffect(()=>{void refresh();const {data:{subscription}}=db.auth.onAuthStateChange(()=>{setTimeout(()=>void refresh(),0);});return()=>subscription.unsubscribe();},[db,refresh]);
 useEffect(()=>{if(!signed)return;const id=setInterval(()=>void refresh(),60000);return()=>clearInterval(id);},[signed,refresh]);
 async function login(){setBusy(true);setMessage("");try{const {error}=await db.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.origin+"/administracion/pedidos"}});setMessage(error?"No se pudo enviar el acceso. Revisá la configuración de correo de Supabase o intentá más tarde.":"Enviamos un enlace de acceso a "+email+". Abrilo desde tu correo para ingresar.");}catch{setMessage("No pudimos conectar. Intentá nuevamente.");}finally{setBusy(false);}}
 async function update(id:string,status:string){setBusy(true);const {error,data}=await db.from("orders").update({status}).eq("id",id).select("id");if(error||!data?.length)setMessage("No pudimos actualizar el estado.");else setOrders(old=>old.map(o=>o.id===id?{...o,status}:o));setBusy(false);}
 if(!signed)return <section className="admin-login"><LockKeyhole size={34}/><span className="eyebrow">SOLO PARA EL EQUIPO</span><h1>Panel de pedidos</h1><p>Ingresá con un correo autorizado para ver y gestionar las órdenes de compra.</p><label>Correo autorizado<select value={email} onChange={e=>setEmail(e.target.value)}>{adminEmails.map(value=><option value={value} key={value}>{value}</option>)}</select></label><button className="button primary" onClick={login} disabled={busy||loading}>{loading?"Comprobando acceso…":busy?"Enviando enlace…":"Recibir enlace de acceso"}</button>{message&&<p role="status">{message}</p>}</section>;
 const visible=orders.filter(o=>(!filter||o.status===filter)&&`${o.number} ${o.customer_name} ${o.phone}`.toLowerCase().includes(search.toLowerCase()));
 return <section className="orders-panel"><div className="section-heading"><div><span className="eyebrow">ENVASES 3G · ADMINISTRACIÓN</span><h1>Órdenes de compra</h1><p>Los pedidos se guardan antes de abrir WhatsApp. El pago se confirma con el cliente.</p></div><div className="admin-actions"><button className="button outline" disabled={loading} onClick={()=>void refresh()}><RefreshCw size={18}/>Actualizar</button><button className="text-link" onClick={async()=>{await db.auth.signOut();setOrders([]);setSigned(false);}}><LogOut size={18}/>Salir</button></div></div>
 <div className="order-stats"><div><strong>{orders.filter(o=>o.status==="nuevo").length}</strong><span>Pedidos nuevos</span></div><div><strong>{orders.length}</strong><span>Últimos pedidos</span></div><div><strong>{currency(orders.filter(o=>o.status==="confirmado"||o.status==="completado").reduce((s,o)=>s+Math.round(Number(o.total)*100),0)/100)}</strong><span>Total confirmado y completado</span></div></div>
 <div className="admin-filters"><label>Buscar pedido<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Número, nombre o teléfono"/></label><label>Estado<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todos los estados</option>{Object.entries(statuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div>
 {message&&<p role="alert" className="form-error">{message}</p>}
 {!visible.length?<div className="empty"><Package size={36}/><h3>{loading?"Cargando pedidos…":"No hay pedidos para mostrar"}</h3><p>Las nuevas órdenes aparecerán acá. Se actualiza cada minuto.</p></div>:visible.map(o=><article className="admin-order" key={o.id}><div className="admin-order-heading"><div><h2>3G-{String(o.number).padStart(6,"0")}</h2><time>{new Date(o.created_at).toLocaleString("es-AR",{timeZone:"America/Argentina/Buenos_Aires"})}</time></div><label>Estado<select aria-label={"Estado del pedido "+o.number} value={o.status} disabled={busy} onChange={e=>void update(o.id,e.target.value)}>{Object.entries(statuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div><p><strong>{o.customer_name}</strong> · <a href={"tel:"+o.phone}>{o.phone}</a></p><div className="order-table-wrap"><table><thead><tr><th>Producto y presentación</th><th>Cantidad</th><th>Precio unitario</th><th>Subtotal</th></tr></thead><tbody>{o.items.map((i,n)=><tr key={n}><td>{i.name}<small>{i.variant}</small></td><td>{i.quantity}</td><td>{currency(i.unitPrice)}</td><td>{currency(i.subtotal)}</td></tr>)}</tbody></table></div><div className="cart-total"><span>Total de productos</span><strong>{currency(Number(o.total))}</strong></div></article>)}<p className="fine">Se muestran los últimos 500 pedidos. Importes antes de descuentos acordados y gastos de entrega.</p></section>;
}
