"use client";
import {useState} from "react";
import {ArrowLeft,Download,FileSpreadsheet,Upload} from "lucide-react";
import Link from "next/link";
type Row={slug:string;variantId:string;price:string;available?:string;minQuantity?:string};
export function PriceImport(){const [rows,setRows]=useState<Row[]>([]);const [error,setError]=useState("");
 function parse(file:File){setError("");if(!/\.(csv|tsv)$/i.test(file.name)){setError("Para esta primera carga usá CSV o TSV exportado desde Excel. Si me enviás un .xlsx, lo convierto y lo incorporo por vos.");return;}const reader=new FileReader();reader.onload=()=>{const text=String(reader.result||"").replace(/^\uFEFF/,"");const lines=text.split(/\r?\n/).filter(Boolean);if(lines.length<2){setError("El archivo no tiene filas para importar.");return;}const sep=lines[0].includes("\t")?"\t":",";const head=lines[0].split(sep).map(x=>x.trim().toLowerCase());const idx=(...names:string[])=>names.map(n=>head.indexOf(n)).find(i=>i>=0)??-1;const s=idx("slug","producto","url");const v=idx("variantid","variant_id","id variante","variante");const p=idx("price","precio","precio ars");if(s<0||v<0||p<0){setError("Faltan columnas. Necesitás: slug, variantId y price. Opcionales: available y minQuantity.");return;}const ai=idx("available","disponible","stock"),mi=idx("minquantity","min_quantity","cantidad minima");const parsed=lines.slice(1).map(line=>line.split(sep)).filter(c=>c[s]&&c[v]&&c[p]).map(c=>({slug:c[s].trim(),variantId:c[v].trim(),price:c[p].trim(),available:ai>=0?c[ai]?.trim():undefined,minQuantity:mi>=0?c[mi]?.trim():undefined}));setRows(parsed);};reader.readAsText(file);
 }
 function download(){const blob=new Blob([JSON.stringify(rows,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="envases3g-precios-revisar.json";a.click();URL.revokeObjectURL(a.href);}
 return <section className="import-panel"><Link href="/administracion/pedidos" className="text-link"><ArrowLeft size={18}/>Volver a pedidos</Link><span className="eyebrow">ENVASES 3G · CARGA DE PRECIOS</span><h1>Importar precios desde Excel</h1><p>Exportá tu planilla como CSV UTF-8 desde Excel y subila acá. La vista previa comprueba el formato antes de actualizar el catálogo.</p><div className="import-schema"><FileSpreadsheet size={28}/><div><strong>Columnas aceptadas</strong><code>slug, variantId, price, available, minQuantity</code><small>Usá el slug y variantId que figuran en el catálogo. Los precios se interpretan en pesos argentinos.</small></div></div><label className="upload-drop"><Upload size={28}/><strong>Elegir archivo CSV o TSV</strong><span>También podés enviarme el .xlsx directamente y lo preparo.</span><input type="file" accept=".csv,.tsv,text/csv,text/tab-separated-values" onChange={e=>e.target.files?.[0]&&parse(e.target.files[0])}/></label>{error&&<p className="form-error">{error}</p>}{rows.length>0&&<><div className="import-summary"><strong>{rows.length} filas listas</strong><span>Revisá algunos registros antes de enviarme la planilla.</span><button className="button primary" onClick={download}><Download size={18}/>Descargar vista previa</button></div><div className="order-table-wrap"><table><thead><tr><th>slug</th><th>variantId</th><th>price</th><th>available</th><th>minQuantity</th></tr></thead><tbody>{rows.slice(0,12).map((r,i)=><tr key={i}><td>{r.slug}</td><td>{r.variantId}</td><td>{r.price}</td><td>{r.available||"—"}</td><td>{r.minQuantity||"—"}</td></tr>)}</tbody></table></div></>}</section>;
}
